[build]
  command = "npm install --legacy-peer-deps && npm run build:netlify"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200