[build]
  command = "npm install --force && npm run build:netlify"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.18.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200